---
title: "Testing Multivariate Regression Trees"
authors: Genoveva Gonzales-Mirelis, Thijs van Son, Rune Halvorsen, Rebecca Ross, Margaret Dolan
date: "Last Rendered on `r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_notebook: 
    toc: yes
    toc_depth: 2
    toc_float: yes
    fig_width: 7
    fig_height: 7
always_allow_html: true 
---

## Packages
Package ‘mvpart’ was removed from the CRAN repository.
Formerly available versions can be obtained from
https://cran.r-project.org/src/contrib/Archive/mvpart/
you will need to download to your computer and then "install from file" before loading the library
```{r}
library(mvpart)
library(dplyr)
```

## Load data
```{r}

## To use the entire dataset use code below, which has been copied from "workflow_deepseaNiN_Start", blocks Data through Data cleaning

env_orig <- read.csv(file.path(dataPath,"inputs/envData_2022-09-13.csv")) %>% as.data.frame
otu_orig <- read.csv(file.path(dataPath,"inputs/widedata_2022-09-13.csv")) %>% as.data.frame

#left join and split to ensure ordered identically

#joinedDat<-otu_orig%>% dplyr::left_join(.,env_orig, by="SampID")
joinedDat<- left_join(otu_orig,env_orig, by=c("SampID"="SampID2"))

otu_sort<-joinedDat %>% select(c(2:351))
env_sort<-joinedDat %>% select(c(2,352:491))

env_sort <- env_sort %>% select(-c("BO22_lightbotmean_bdmean",
                               "BO22_lightbotltmax_bdmean",
                               "BO22_lightbotltmin_bdmean",
                               "BO22_lightbotrange_bdmean"))

## ALternatively, do only within a prespecified group of samples
# env_sort <- read.csv(file.path(dataPath,"inputs/LDensNoSB_env_sort_2022-09-26.csv")) %>% as.data.frame
# otu_sort <- read.csv(file.path(dataPath,"inputs/LDensNoSB_otu_sort_2022-09-26.csv")) %>% as.data.frame


## Complete cases and real columns
otuCompl <- otu_sort %>%
  select(-c(1:which(colnames(otu_sort)=="Acesta_excavata")-1)) 
  #filter(complete.cases(.))
  
envCompl <- env_sort %>%
  select(-c(1:which(colnames(env_sort)=="bathy")-1)) 
  #filter(complete.cases(.))
 
## Removing observations with less than 4 OTUs
sel <- rowSums(otuCompl[, -c(1:2)]) >= 4
otuSel <- otuCompl[sel, ]
envSel <- envCompl[sel, ]

## Removing phosphate
#envSel <- envSel %>% select(-phosphate_mean.tif)

dim(otuSel); dim(envSel)
```

## Analysis
```{r}
Y=otuSel
X=envSel %>%
  select(-c("coords.x1", "coords.x2","optional",
            "X.y","Y"))

x_mn <- min(Y[Y > 0])
x_mx <- max(Y)
rng <- 6           # abundance range
w <- log(rng) / (log(x_mx) - log(x_mn))
a <- x_mn^(-w)
# otu_6 <- a * dt[, -c(1:3)]^w
otuSel_6 <- a * Y^w
range(otuSel_6)
Y<-otuSel_6
  


# df2 = cor(X)
# hc = findCorrelation(df2, cutoff=0.7) # putt any value as a "cutoff" 
# hc = sort(hc)
# new_X = X[,-c(hc)]


mvtree <- mvpart(data.matrix(Y) ~ ., data=X, xv="1se", xvmult=100)
                                                #new_X), xv="1se", xvmult=10)
mvtree
```

### Another way of doing the same thing...
```{r}
library(oce)

envSel$swDensRob_avs<-swRho(salinity=envSel$Smean_Robinson,
                         temperature=envSel$Tmean_Robinson,
                         pressure=(envSel$bathy*-1),
                         eos="unesco")

abundance <- data.matrix(otuSel_6)
environmental_variables <- envSel


formula <- as.formula(paste("abundance ~", paste0(colnames(environmental_variables), collapse="+")))

# Set a new seed for random numbers to ensure results are reproducible
set.seed(1221)

# See `?mvpart()` for argument details
mvpart_run <- mvpart(
  form = formula,
  #form = abundance ~ swDensRob_avs,
  data = environmental_variables,
  all.leaves = TRUE,  # annotate all nodes
  #rsq = TRUE,  # give "rsq" plot
  #pca = TRUE,  # plot PCA of group means and add species and site information
  #wgt.ave.pca = TRUE  # plot weighted averages acorss sites for species
)
mvpart_run
```


## testing github
```{r}
plot(cars)
```
